Kernel360/Kernel360-KDEV4-ZIPLINE-FE

- src/components/layout/Layout.tsx
- src/main.css
> fix: import tailwind css

- src/App.tsx
- src/components/NavigationBar.tsx
- src/components/layout/PrivateRoute.tsx
- src/pages/AuthPage.tsx
- src/pages/CustomerListPage/CustomerListPage.tsx
- src/pages/CustomerListPage/index.ts
> feat: 상단바 추가

- src/components/TextField.tsx
- src/hooks/useInput.ts
- src/pages/CustomerListPage/CustomerAddButtonList/CustomerAddButtonList.tsx
- src/pages/CustomerListPage/CustomerAddButtonList/CustomerAddModal/CustomerAddModal.tsx
- src/pages/CustomerListPage/CustomerAddButtonList/CustomerAddModal/index.ts
- src/pages/CustomerListPage/CustomerAddButtonList/index.ts
- src/pages/CustomerListPage/CustomerListPage.tsx
- src/pages/CustomerListPage/CustomerTable/CustomerTable.tsx
- src/pages/CustomerListPage/CustomerTable/index.ts
- src/pages/SignUpPage/NameInput.tsx
> design: 고객 목록 페이지

- src/apis/apiClient.ts
> https://github.com/Kernel360/Kernel360-KDEV4-ZIPLINE-FE/issues/21
>
>
> (fix) 커스텀 axios client에서 동적으로 Authorization 헤더 넣어주도록 수정

- package-lock.json
- package.json
- src/components/TextField.tsx
- src/hooks/useInput.ts
- src/pages/PrivatePropertyListPage/PrivatePropertyListPage.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyAddButtonList.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyAddModal/DaumPost/DaumPost.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyAddModal/DaumPost/index.ts
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyAddModal/PropertyAddModal.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyAddModal/index.ts
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/index.ts
- src/utils/numberUtil.ts
- tsconfig.json
- vite.config.ts
> feat: 개인 매물 등록 기능 추가

- src/App.tsx
- src/components/Button.tsx
- src/components/NavigationBar.tsx
- src/components/layout/PrivateRoute.tsx
- src/pages/MyPage/EditSurveyPage/EditSurveyPage.tsx
- src/pages/MyPage/EditSurveyPage/MultipleChoiceAdd/MultipleChoiceAdd.tsx
- src/pages/MyPage/EditSurveyPage/MultipleChoiceAdd/index.ts
- src/pages/MyPage/EditSurveyPage/SingleChoiceAdd/SingleChoiceAdd.tsx
- src/pages/MyPage/EditSurveyPage/SingleChoiceAdd/index.ts
- src/pages/MyPage/EditSurveyPage/index.ts
- src/pages/MyPage/MyPage.tsx
- src/pages/MyPage/index.ts
> feat: 설문 폼 수정 페이지 추가

- src/pages/PrivatePropertyListPage/PrivatePropertyListPage.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyAddButtonList.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyAddModal/PropertyAddModal.tsx
- src/pages/PrivatePropertyListPage/PropertyTable/PropertyTable.tsx
> feat:개인 매물 조회 api 연결

- src/pages/CustomerListPage/CustomerAddButtonList/CustomerAddButtonList.tsx
- src/pages/CustomerListPage/CustomerAddButtonList/CustomerAddModal/CustomerAddModal.tsx
- src/pages/CustomerListPage/CustomerListPage.tsx
- src/pages/CustomerListPage/CustomerTable/CustomerTable.tsx
> feat: 고객 목록 조회 api 연결

- package-lock.json
- package.json
- src/components/NavigationBar.tsx
- src/components/layout/PrivateRoute.tsx
- src/pages/MyPage/MyPage.tsx
- src/stores/useUserStore.ts
- tsconfig.json
- vite.config.ts
> feat: 유저 정보 전역 변수로 관리

- src/App.tsx
- src/apis/apiClient.ts
- src/components/layout/NewbieSurveyRoute.tsx
- src/pages/ErrorPage/ErrorPage.tsx
- src/pages/ErrorPage/index.ts
- src/pages/SubmitSurveyPage/SubmitSurveyPage.tsx
- src/pages/SubmitSurveyPage/index.ts
- src/pages/SubmitSurveySuccessPage/SubmitSurveySuccessPage.tsx
- src/pages/SubmitSurveySuccessPage/index.ts
> feat: 설문 제출 페이지 구현

- src/App.tsx
- src/pages/ContractListPage/ContractAddButtonList/ContractAddModal/ContractAddModal.tsx
- src/pages/CustomerDetailPage/CounselTable/CounselTable.tsx
- src/pages/CustomerDetailPage/CounselTable/index.ts
- src/pages/CustomerDetailPage/CustomerDetailPage.tsx
- src/pages/CustomerDetailPage/CustomerInfo/CustomerInfo.tsx
- src/pages/CustomerDetailPage/CustomerInfo/index.ts
- src/pages/CustomerDetailPage/index.ts
- src/pages/CustomerListPage/CustomerTable/CustomerTable.tsx
- src/pages/MyPage/EditSurveyPage/EditSurveyPage.tsx
- src/pages/PrivatePropertyListPage/PropertyTable/PropertyTable.tsx
- src/pages/PublicPropertyListPage/PublicPropertyListPage.tsx
- src/pages/PublicPropertyListPage/PublicPropertyTable/PublicPropertyTable.tsx
- src/pages/SubmitSurveySuccessPage/SubmitSurveySuccessPage.tsx
> feat: 고객 정보 상세 조회 페이지 구현

- src/pages/SignUpPage/PhoneNumberInput.tsx
> feat:전화번호 입력 오토 포매팅

- src/components/NavigationBar/NavigationBar.tsx
- src/components/layout/PrivateRoute.tsx
> (fix) 레이아웃 오류 수정

- src/App.tsx
- src/components/CreateModal/CreateModal.tsx
- src/components/ScheduleDetailModal/ScheduleDetailModal.tsx
- src/interfaces/schedule.ts
- src/pages/BulkMessagePage/BulkMessagePage.tsx
- src/pages/DashboardPage/DashboardPage.tsx
- src/pages/MessageHistoryPage/MessageHistoryPage.tsx
- src/pages/MessageHistoryPage/index.ts
- src/pages/MessageTemplatePage/MessageTemplatePage.tsx
- src/pages/MessageTemplatePage/index.ts
- src/pages/SchedulePage/SchedulePage.tsx
> design: 문자 관련 페이지 구현

- src/components/PageHeader/PageHeader.tsx
- src/hooks/useDebounce.ts
- src/pages/CustomerDetailPage/CustomerDetailPage.tsx
- src/pages/CustomerListPage/CustomerAddButtonList/CustomerAddButtonList.tsx
- src/pages/CustomerListPage/CustomerAddButtonList/CustomerAddModal/CustomerAddModal.tsx
- src/pages/CustomerListPage/CustomerFilterModal/CustomerFilterModal.tsx
- src/pages/CustomerListPage/CustomerListPage.tsx
- src/pages/CustomerListPage/CustomerTable/CustomerTable.tsx
> #46
> 고객 목록 조회 
> 고객 목록 필터링
> 고객 상세 페이지
> feat: 고객 목록 및 상세 페이지 기능 추가 및 필터링 기능 구현

- src/App.tsx
- src/components/NavigationBar/NavigationBar.tsx
- src/components/ScheduleDetailModal/ScheduleDetailModal.tsx
- src/pages/ContractDetailPage/ContractDetailPage.tsx
- src/pages/ContractDetailPage/index.ts
- src/pages/CounselListPage/CounselListPage.tsx
- src/pages/CounselListPage/index.ts
- src/pages/DashboardPage/DashboardPage.tsx
- src/pages/SchedulePage/SchedulePage.tsx
> feat: 대시보드 관련 api 연결

- package-lock.json
- package.json
- src/pages/PublicPropertyListPage/PropertyFilterComponent/PropertyFilterComponent.tsx
- src/pages/PublicPropertyListPage/PublicPropertyFilterModal/PublicPropertyFilterModal.tsx
- src/pages/PublicPropertyListPage/PublicPropertyListPage.tsx
- src/pages/PublicPropertyListPage/PublicPropertyTable/PublicPropertyTable.tsx
> (feat)공개매물 페이지

- src/App.tsx
- src/pages/BulkMessagePage/BulkMessagePage.tsx
- src/pages/CounselDetailPage/CounselDetailPage.tsx
- src/pages/CounselDetailPage/index.ts
- src/pages/CounselListPage/CounselListPage.tsx
- src/pages/CustomerDetailPage/CustomerDetailPage.tsx
- src/pages/CustomerDetailPage/CustomerInfo/CustomerInfo.tsx
- src/pages/CustomerListPage/CustomerAddButtonList/CustomerAddButtonList.tsx
- src/pages/CustomerListPage/CustomerListPage.tsx
- src/pages/DashboardPage/DashboardPage.tsx
- src/pages/MessageTemplatePage/MessageTemplatePage.tsx
- src/pages/SchedulePage/SchedulePage.tsx
- src/utils/numberUtil.ts
> design: 상담 관련 페이지 작성

- package-lock.json
- package.json
- src/pages/MyPage/MyPage.tsx
- src/stores/useUserStore.ts
> #50
> 마이페이지 : 회원정보 수정, 자동 문자 설정,  설문 url 주소 복사 및 QR 생성
> 라이브러리 설치 필요: `npm install react-qr-code`
> (feat) 마이페이지 구현

- src/pages/MyPage/MyPage.tsx
> (fix)qr url 수정

- src/pages/PublicPropertyListPage/PublicPropertyFilterModal/PublicPropertyFilterModal.tsx
> (fix)error

- src/pages/MessageHistoryPage/MessageHistoryPage.tsx
> fix: 문자 발송 내역 페이지를 서버 응답에 맞춰 보여줄 수 있도록 수정

- src/apis/apiClient.ts
> #73 
> 로그인 요청(/users/login)에서 401 응답 시 reissue 호출되지 않도록 분기 처리
> 로그인 실패 시 이전 유저의 refreshToken이 재사용되는 문제 방지
> fix: 로그인 API 요청 시 401 에러 발생할 때 reissue 호출 방지

- src/components/NavigationBar/NavigationBar.tsx
> chore: 새로만들기 메뉴 주석 처리

- src/pages/MessageHistoryPage/MessageHistoryPage.tsx
- src/pages/MyPage/MyPage.tsx
> chore: 아직 서버에서 구현되지 않는 기능에 대한 ui 주석 처리

- src/pages/PublicPropertyListPage/PublicPropertyTable/PublicPropertyTable.tsx
> (fix)disable url

- src/pages/PublicPropertyListPage/PublicPropertyTable/PublicPropertyTable.tsx
> (fix)불필요 정보 비활성화 주소 비활성화

- src/pages/PublicPropertyListPage/PublicPropertyListPage.tsx
- src/pages/PublicPropertyListPage/PublicPropertyTable/PublicPropertyTable.tsx
> ex) #83
>정렬시 문제점들 수정
문제1: 정렬시 보여주고 안보여줘야되는 컬럼들에 대한 처리를 상태관리식으로 바꿔서 가독성을 향상시키고 원래 있던 로직상에 문제를 해결해서 정렬후 테이블이깨지는 문제를 수정했습니다.
문제2: 정렬시 최솟값을 0부터 가져오면 사실상 없는 무의미한 빈데이터들이 오기때문에 최소값 1부터 찾도록 로직을 수정했습니다. 기존 상태에 영향을 주지않도록 최종 url 전송시에 적용되는 별도의 함수를 사용했습니다. 
사용성 개선을 위해 정렬 리셋버튼 추가(sort{id:ASC})
>
> (hotfix)fixed public item table error

- src/pages/CounselDetailPage/CounselDetailPage.tsx
- src/pages/CounselDetailPage/styles/CounselDetailPage.module.css
- src/pages/CounselListPage/CounselListPage.tsx
- src/pages/CounselListPage/CounselModal.tsx
- src/pages/CounselListPage/styles/CounselListPage.module.css
> #77 
> 상담 목록 페이지 필터링 추가
> 상담 상세 조회 페이지 구현
> feat: 상담 목록, 상담 상세 조회

- src/pages/ContractDetailPage/ContractDetailContent.tsx
- src/pages/ContractListPage/ContractAddButtonList/ContractEditModal/ContractEditModal.tsx
- src/pages/ContractListPage/ContractListPage.tsx
- src/pages/ContractListPage/ContractTable/ContractTable.tsx
> fix: 계약 버그 수정

- src/pages/CustomerListPage/CustomerListPage.tsx
- src/pages/CustomerListPage/CustomerTable/CustomerTable.tsx
- src/pages/CustomerListPage/CustomerTable/DeleteConfirmModal.tsx
#46
* 고객 목록 페이지 디자인 수정
* 고객 이름, 전화번호, 역할, 라벨을 목록 페이지에서 수정할 수 있도록 코드 추가
* 검색 조건 바뀔 때마다 화면 깜박이는 버그 수정
>
> feat: 고객 목록 페이지 디자인 수정

- src/components/RegionSelect/RegionSelect.tsx
- src/components/RegionSelect/index.ts
- src/pages/CustomerDetailPage/CustomerDetailPage.tsx
> design: 고객 상세 페이지 디자인 수정

- src/components/RegionSelect/RegionSelect.tsx
- src/pages/CustomerDetailPage/CustomerDetailPage.tsx
> feat: 고객 정보 수정 페이지에 지역 선택 로직 수정

- src/pages/ContractDetailPage/ContractDetailPage.tsx
- src/pages/PrivatePropertyListPage/AgentPropertyDetailPage/AgentPropertyDetailContent.tsx
- src/pages/PrivatePropertyListPage/AgentPropertyDetailPage/AgentPropertyDetailPage.tsx
- src/pages/PrivatePropertyListPage/AgentPropertyDetailPage/styles/AgentPropertyDetailPage.styles.ts
- src/pages/PrivatePropertyListPage/PrivatePropertyListPage.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyAddModal/PropertyAddModal.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyEditModal/DaumPost/DaumPost.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyEditModal/DaumPost/index.ts
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyEditModal/PropertyEditModal.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyEditModal/index.ts
- src/pages/PrivatePropertyListPage/PropertyFilterModal/PropertyFilterModal.tsx
- src/pages/PrivatePropertyListPage/PropertyTable/PropertyTable.tsx
- src/pages/PrivatePropertyListPage/styles/PrivatePropertyListPage.styles.ts
- src/types/AgentPropertyFilterRequest.ts
> feat: 매물 페이지

- src/pages/DashboardPage/DashboardPage.tsx
- src/pages/DashboardPage/SurveyDetailModal/SurveyDetailModal.tsx
- src/pages/DashboardPage/SurveyDetailModal/index.ts
> fix: 대시보드 디자인 수정

- src/pages/ContractDetailPage/ContractDetailContent.tsx
- src/pages/ContractListPage/ContractAddButtonList/ContractAddModal/ContractAddModal.tsx
- src/pages/ContractListPage/ContractAddButtonList/ContractEditModal/ContractEditModal.tsx
- src/pages/ContractListPage/ContractTable/ContractTable.tsx
> feat: 고객 여러명 등록/수정 및 조회

- src/pages/ContractListPage/ContractAddButtonList/ContractAddModal/ContractAddModal.tsx
- src/pages/PrivatePropertyListPage/PrivatePropertyListPage.tsx
> fix: 중복등록 에러처리

- src/pages/ContractDetailPage/ContractDetailPage.tsx
- src/pages/ContractListPage/ContractAddButtonList/ContractEditModal/ContractEditModal.tsx
- src/pages/ContractListPage/ContractListPage.tsx
- src/pages/ContractListPage/styles/ContractListPage.module.css
- src/pages/CounselListPage/CounselListPage.tsx
- src/pages/CounselListPage/styles/CounselListPage.module.css
- src/pages/PrivatePropertyListPage/PrivatePropertyListPage.tsx
- src/pages/SchedulePage/SchedulePage.tsx
> fix: ui 버튼 및 매물 목록 필터링 수정

- src/components/PageHeader/PageHeader.tsx
- src/pages/ContractListPage/ContractListPage.tsx
> design: pageHeader 컴포넌트에 sticky 스타일 추가

- src/pages/MessageHistoryPage/MessageHistoryPage.tsx
> design: 문자 발송 내역 페이지 디자인 수정

- src/pages/BulkMessagePage/BulkMessagePage.tsx
- src/pages/MessageHistoryPage/MessageHistoryPage.tsx
- src/pages/MessageTemplatePage/MessageTemplatePage.tsx
> design: 문자 관련 페이지 디자인 수정

- src/pages/ContractDetailPage/ContractDetailPage.tsx
- src/pages/ContractListPage/ContractAddButtonList/ContractEditModal/ContractEditModal.tsx
- src/pages/ContractListPage/ContractTable/ContractTable.tsx
- src/pages/ContractListPage/styles/ContractListPage.module.css
- src/pages/CounselDetailPage/CounselDetailPage.tsx
- src/pages/CounselDetailPage/styles/CounselDetailPage.module.css
- src/pages/CounselListPage/CounselListPage.tsx
- src/pages/CounselListPage/styles/CounselListPage.module.css
- src/pages/CustomerDetailPage/Tables/ConsultationTable.tsx
- src/pages/CustomerDetailPage/Tables/ContractTable.tsx
- src/pages/CustomerDetailPage/Tables/PropertyTable.tsx
- src/pages/CustomerListPage/CustomerAddButtonList/CustomerAddButtonList.tsx
- src/pages/CustomerListPage/CustomerListPage.tsx
- src/pages/CustomerListPage/CustomerTable/CustomerTable.tsx
- src/pages/PrivatePropertyListPage/AgentPropertyDetailPage/AgentPropertyDetailPage.tsx
- src/pages/PrivatePropertyListPage/AgentPropertyDetailPage/styles/AgentPropertyDetailPage.styles.ts
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyAddButtonList.tsx
- src/pages/PrivatePropertyListPage/PropertyFilterModal/PropertyFilterModal.tsx
- src/pages/PrivatePropertyListPage/PropertyTable/PropertyTable.tsx
- src/pages/PrivatePropertyListPage/styles/PrivatePropertyListPage.styles.ts
> fix: ui 및 버그 수정

- src/pages/PrivatePropertyListPage/PropertyTable/PropertyTable.tsx
- src/pages/PublicPropertyListPage/PublicPropertyListPage.tsx
- src/pages/PublicPropertyListPage/PublicPropertyTable/PublicPropertyTable.tsx
> fix: 공개매물 페이지 수정

- src/pages/PrivatePropertyListPage/AgentPropertyDetailPage/AgentPropertyDetailPage.tsx
> chore: 카카오맵 api 호출 url을 http -> https로 수정

- package-lock.json
- package.json
- src/pages/CustomerListPage/CustomerAddButtonList/CustomerAddButtonList.tsx
- src/pages/CustomerListPage/CustomerAddButtonList/CustomerBulkUploadModal.tsx
- src/pages/CustomerListPage/CustomerListPage.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/BulkUploadModal.tsx
- src/pages/PrivatePropertyListPage/PropertyAddButtonList/PropertyAddButtonList.tsx
> feat: 고객/매물 대량 업로드 기능 추가

- src/pages/DashboardPage/SurveyDetailModal/SurveyDetailModal.tsx
> fix: survey 대시보드 조회 수정

- src/pages/MyPage/EditSurveyPage/EditSurveyPage.tsx
> fix: 설문 질문 id 지정

- src/pages/PublicPropertyListPage/PublicPropertyListPage.tsx
- src/pages/PublicPropertyListPage/PublicPropertyTable/PublicPropertyTable.tsx
> fix: 공급면적 정렬 null값 제거

- src/pages/PublicPropertyListPage/PublicPropertyListPage.tsx
> fix: 주소 불러오기

- src/pages/PublicPropertyListPage/PublicPropertyTable/PublicPropertyTable.tsx
> fix: 플랫폼 표기

- src/pages/PrivatePropertyListPage/PropertyTable/PropertyTable.tsx
- src/pages/PublicPropertyListPage/PublicPropertyTable/PublicPropertyTable.tsx
> fix: 매물 타입 스타일 변경

- src/pages/PublicPropertyListPage/PublicPropertyTable/PublicPropertyTable.tsx
> fix: 공개매물 태그 스타일 변경

- src/pages/SignInPage/SignInPage.tsx
> chore: 로그인 페이지에 테스트용 계정 소개 영역 추가

- src/pages/DashboardPage/DashboardPage.tsx
> feat: 대시보드 - 상담 카드에 안내 문구 추가

- src/pages/CustomerDetailPage/CustomerDetailPage.tsx
- src/pages/CustomerListPage/CustomerAddButtonList/CustomerAddModal/CustomerAddModal.tsx
> fix: 고객 등록 시 toast 알람 추가

- src/pages/SchedulePage/AddScheduleModal/AddScheduleModal.tsx
> fix: 일정 생성 시 description optional하게 받을 수 있도록 수정

- src/components/PageHeader/PageHeader.tsx
> feat: 헤더에 뒤로가기 버튼 스타일 추가

- src/pages/CustomerDetailPage/CustomerDetailPage.tsx
- src/pages/MyPage/MyPage.tsx
- src/pages/SignUpPage/PhoneNumberInput.tsx
- src/pages/SubmitSurveyPage/SubmitSurveyPage.tsx
- src/utils/numberUtil.ts
> feat: 모든 전화번호 인풋에 자동 포맷팅 적용
